### ISSUE TITLE
Skip Missing Blocks

### ISSUE THREAD

**Issue by stwiname** [subquery/subql-near#4]
## Description

Near seems to skip blocks from time to time. We have the `bypassBlocks` feature but this is impractical for all projects to keep this list. 

We should detect skipped blocks by checking for a specific error and skip over them automatically

## Example Error

```
Failed to fetch blocks from queue Error: [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 81003306 Cause: Unknown at JsonRpcProvider.<anonymous> (/usr/local/lib/node_modules/@subql/node-near/node_modules/near-api-js/lib/providers/json-rpc-provider.js:366:35) at Generator.next (<anonymous>) at fulfilled (/usr/local/lib/node_modules/@subql/node-near/node_modules/near-api-js/lib/providers/json-rpc-provider.js:5:58) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Further information

https://stackoverflow.com/questions/71197370/why-blocks-are-missing-or-skipped-on-near

**Comment by stwiname** [comment]
Fixed in https://github.com/subquery/subql-near/pull/5
